from .google import GoogleConnector
from .youtube import YouTubeConnector
from .arxiv import ArxivConnector
from .udemy import UdemyConnector
from .coursera import CourseraConnector
from .edx import EdxConnector
from .khan_academy import KhanAcademyConnector
from .harvard_online import HarvardOnlineConnector
from .mit_ocw import MitOcwConnector